#!/bin/sh
command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. You need to install 'git-lfs' locally to be able to use this repository.\n"; exit 2; }
git lfs post-commit "$@"
